addSbtPlugin("io.get-coursier" %% "sbt-coursier" % "1.0.2")
addSbtPlugin("com.geirsson" %% "sbt-scalafmt" % "1.6.0-RC1")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.5.10")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.3.4")
addSbtPlugin("com.eed3si9n" % "sbt-buildinfo" % "0.9.0")
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.7")
